spring.application.name=${SPRING_APPLICATION_NAME}

# Database
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=${DB_DRIVER}

# JPA
spring.jpa.database-platform=${DB_DIALECT}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}

# JWT
jwt.secretKey=${JWT_SECRET_KEY}

# Spring AI (Google Gemini)
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=${GOOGLE_GENAI_MODEL}

# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# GitHub OAuth
github.client.id=${GITHUB_CLIENT_ID}
github.client.secret=${GITHUB_CLIENT_SECRET}
github.app.id=${GITHUB_APP_ID}

# Google OAuth
google.api.client.id=${GOOGLE_CLIENT_ID}

spring.sendgrid.api-key=${SENDGRID_API_KEY}
